default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: logu_development
test:
  <<: *default
  database: logu_test
production:
  <<: *default
  database: logu_production
